networks:
    insomnia-demo-net:

services:

    kong:
        image: kong/kong-gateway:3.9.0.1
        container_name: kong
        hostname: kong
        environment:
            KONG_ROLE: data_plane
            KONG_DATABASE: off
            KONG_VITALS: off
            KONG_CLUSTER_MTLS: pki
            KONG_CLUSTER_CONTROL_PLANE: ${KONG_CLUSTER_CONTROL_PLANE}
            KONG_CLUSTER_SERVER_NAME: ${KONG_CLUSTER_SERVER_NAME}
            KONG_CLUSTER_TELEMETRY_ENDPOINT: ${KONG_CLUSTER_TELEMETRY_ENDPOINT}
            KONG_CLUSTER_TELEMETRY_SERVER_NAME: ${KONG_CLUSTER_TELEMETRY_SERVER_NAME}
            KONG_CLUSTER_CERT: /etc/secrets/tls.crt
            KONG_CLUSTER_CERT_KEY: /etc/secrets/tls.key
            KONG_LUA_SSL_TRUSTED_CERTIFICATE: system
            KONG_KONNECT_MODE: on
        networks:
            - insomnia-demo-net
        ports:
            - "8000:8000" 
            - "8443:8443"
        healthcheck:
            test: ["CMD", "kong", "health"]
            interval: 10s
            timeout: 10s
            retries: 10
        restart: always
        volumes:
        - ./config/tls:/etc/secrets


    employees-directory:
        image: davidmacdonaldkong/employees-directory:f542507acb0fb92076c45d91dfce122f5ec8d9a8
        container_name: employees-directory
        hostname: employees-directory
        networks:
            - insomnia-demo-net
        ports:
            - "8090:8080"
        restart: always


    insomnia-mock:
        image: ghcr.io/kong/insomnia-mockbin
        container_name: insomnia-mock
        environment:
            MOCKBIN_REDIS: "redis://redis:6379"
            MOCKBIN_QUIET: "false"
            MOCKBIN_PORT: "9090"
            MOCKBIN_REDIS_EXPIRE_SECONDS: 1000000000
        networks:
            - insomnia-demo-net
        ports:
        - "9090:9090"

    redis:
        image: redis
        container_name: redis
        networks:
            - insomnia-demo-net

    keycloak:
        image: quay.io/keycloak/keycloak:23.0.6
        container_name: keycloak
        command: "start-dev --import-realm"
        environment:
            KC_HOSTNAME: localhost
            KC_HOSTNAME_PORT: 8080
            KC_HOSTNAME_STRICT_BACKCHANNEL: false
            KC_HTTP_ENABLED: true
            KC_HOSTNAME_STRICT_HTTPS: false
            KC_HEALTH_ENABLED: true
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
        - 8080:8080
        restart: always
        networks:
        - insomnia-demo-net
        volumes:
            - ./config/keycloak:/opt/keycloak/data/import

    httpbin:
        image: kennethreitz/httpbin
        container_name: httpbin
        hostname: httpbin
        networks:
            - insomnia-demo-net
        ports:
            - "9000:80"